name: Run Pytest

on:
  push:
    branches: [ "main" ]  
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code #descargar el repo
      uses: actions/checkout@v3

    - name: Set up Python #configurar python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies #instalar dependencias
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: |
        pytest